### PR TITLE
Second Milestone Project

### PR DESCRIPTION
**Pull request by haraphat01**
This is an updated project for the second milestone for the Tic Toc Toe Game

- We've defined how to get user inputs for the two players.

- Defined our board will be displayed.

- We've also defined the functions needed.

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great start @team :clap: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

image

- **[REQUIRED]** The game crashes when I try to start it. :pray:  fix it.

- **[REQUIRED]** Fix the errors detected by the linter :red_circle: . All checks should pass.

- **[NEXT MILESTONE]** In this milestone, not everything should work, the point is to setup the basic UI interactions with the user. As for the next milestone, you will have to transform the game logic code that you've written in main.rb into classes and put them in /lib directory. 

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by haraphat01** [comment]
- Fixed the Lint Errors

- Fixed The Crashing Game Upon Starting

- Displayed The Board

**Comment by lekegitrepo** [comment]
#### Hi @haraphat01 and @DickensJuma :clap: :clap:
#### Good job. You suppose to show that you thought about these in the project using mockups, comments, or implementation.

Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

* [ ] `[OPTIONAL]` game asks players for their names
* [ ] `[REQUIRED]` game tells which player turn it is
* [ ] `[REQUIRED]` game asks the player to select from available moves
* [ ] `[REQUIRED]` game informs player if the selected move is invalid
* [ ] `[REQUIRED]` game displays board after the player move
* [ ] `[REQUIRED]` game informs player if the selected move is a winning move
* [ ] `[REQUIRED]` game informs player if the selected move is a draw move
* [ ] `[REQUIRED]` game repeats all actions for the next player's move

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by haraphat01** [comment]
This is our completed project for the Second Milestone Project under the OOP curriculum.

All issues raised by the TSE has been fixed.

Kindly check for your kind approval.

Thanks

**Review by nikasulo — APPROVED** [review]
# Great work! @haraphat01 and @DickensJuma 🎖️ 
Please merge and keep moving forward, I wish you the very best and see you at the top 🚀

**Pull request merged**
